Controllers/CourseController.cs
using BullDoghs.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BullDoghs.Controllers
{
    public class CourseController : Controller

    {
        private readonly Team105DBContext _team105DBContext;

        public CourseController(Team105DBContext courseContext)
        {
            _team105DBContext = courseContext;
        }
        public IActionResult CourseView()
        {
            var courses = _team105DBContext.tbCourseSections.Include(p => p.CourseTitle_FKNavigation).Include(p => p.TeacherID_FKNavigation);
            return View(courses.ToList());
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _team105DBContext.tbCourseSections == null)
            {
                return RedirectToAction("CourseView");
            }

            var courses = await _team105DBContext.tbCourseSections.Include(p => p.CourseTitle_FKNavigation).Include(p => p.TeacherID_FKNavigation)
                .FirstOrDefaultAsync(m => m.CourseSectionID_PK == id);

            if (courses == null)
            {
                return RedirectToAction("CourseView");
            }

            return View(courses);
        }

        [HttpGet]
        public IActionResult RegistrationView()
        {
            
            var registrations = _team105DBContext.tbRegistrations.Include(p => p.StudentID_FKNavigation).Include(p => p.CourseSectionID_FKNavigation).Include(p => p.CourseSectionID_FKNavigation.CourseTitle_FKNavigation);

            return View(registrations.ToList());
        }
        [HttpPost]
        public IActionResult RegistrationView(string courseName, string status, string studentFirstName)
        {
            var registrations = from p in _team105DBContext.tbRegistrations.Include(p => p.StudentID_FKNavigation).Include(p => p.CourseSectionID_FKNavigation).Include(p => p.CourseSectionID_FKNavigation.CourseTitle_FKNavigation) select p;
            
            ViewData["CourseNameFilter"] = courseName;
            ViewData["CourseStatusFilter"] = status;
            ViewData["StudentNameFilter"] = studentFirstName;


            if (!string.IsNullOrEmpty(courseName))
            {
                registrations = registrations.Where(p => p.CourseSectionID_FKNavigation.CourseTitle_FKNavigation.CourseTitle_PK.Contains(courseName));
            }

            if (!string.IsNullOrEmpty(status))
            {
                registrations = registrations.Where(p => p.CourseStatus.Equals(status));
            }

            if (!string.IsNullOrEmpty(studentFirstName))
            {
                registrations = registrations.Where(p => p.StudentID_FKNavigation.StudentName.Contains(studentFirstName));
            }


            return View(registrations.OrderBy(p => p.CourseRegistrationID_PK));
        }



    }
}

Controllers/StudentPortController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BullDoghs.Models;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;

namespace BullDoghs.Controllers
{
    public class StudentPortController : Controller
    {
        private readonly Team105DBContext _context;

        public StudentPortController(Team105DBContext context)
        {
            _context = context;
        }

        // GET: StudentPort
        [Authorize(Roles = "Student")]
        public async Task<IActionResult> StudentView()
        {
            //int userPK = Int32.Parse(HttpContext.User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Sid).Value);

            String userName = HttpContext.User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Name).Value;

            var team105DBContext = _context.tbRegistrations.Include(t => t.CourseSectionID_FKNavigation).Include(t => t.CourseSectionID_FKNavigation.TeacherID_FKNavigation).Include(t => t.CourseSectionID_FKNavigation.CourseTitle_FKNavigation).Include(t => t.StudentID_FKNavigation).Where(u => u.StudentID_FKNavigation.StudentName == userName);

            return View(await team105DBContext.ToListAsync());
        }

        
    }
}

Controllers/TeacherPortController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BullDoghs.Models;
using Microsoft.AspNetCore.Authorization;
using System.Data;
using System.Security.Claims;
using Microsoft.Extensions.Configuration.UserSecrets;
using Microsoft.Build.Evaluation;

namespace BullDoghs.Controllers
{
    public class TeacherPortController : Controller
    {
        private readonly Team105DBContext _context;

        public TeacherPortController(Team105DBContext context)
        {
            _context = context;
        }

        // GET: TeacherPort
        [Authorize(Roles = "Teacher")]
        public async Task<IActionResult> Index()
        {
            String userName = HttpContext.User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Name).Value;

            var team105DBContext = _context.tbCourseSections.Include(t => t.CourseTitle_FKNavigation).Include(t => t.TeacherID_FKNavigation).Where(u => u.TeacherID_FKNavigation.TeacherName == userName);
            return View(await team105DBContext.ToListAsync());
        }

        // GET: TeacherPort/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.tbCourseSections == null)
            {
                return NotFound();
            }

            var tbCourseSection = await _context.tbCourseSections
                .Include(t => t.CourseTitle_FKNavigation)
                .Include(t => t.TeacherID_FKNavigation)
                .FirstOrDefaultAsync(m => m.CourseSectionID_PK == id);
            if (tbCourseSection == null)
            {
                return NotFound();
            }

            return View(tbCourseSection);
        }

        // GET: TeacherPort/Create
        public IActionResult Create()
        {
            String userName = HttpContext.User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Name).Value;

            ViewData["CourseTitle_FK"] = new SelectList(_context.tbCourses, "CourseTitle_PK", "CourseTitle_PK");
            ViewData["TeacherID_FK"] = new SelectList(_context.tbTeachers.Where(n => n.TeacherName == userName), "TeacherID_PK", "TeacherID_PK");
            return View();
        }

        // POST: TeacherPort/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CourseSectionID_PK,Course_day,Course_time,AttendentNumber,ClassRoom,TeacherID_FK,CourseTitle_FK")] tbCourseSection tbCourseSection)
        {
            
            if (ModelState.IsValid)
            {
                _context.Add(tbCourseSection);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            String userName = HttpContext.User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Name).Value;

            ViewData["CourseTitle_FK"] = new SelectList(_context.tbCourses, "CourseTitle_PK", "CourseTitle_PK", tbCourseSection.CourseTitle_FK);
            ViewData["TeacherID_FK"] = new SelectList(_context.tbTeachers.Where(n => n.TeacherName == userName), "TeacherID_PK", "TeacherID_PK", tbCourseSection.TeacherID_FK);
            return View(tbCourseSection);
        }

        // GET: TeacherPort/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.tbCourseSections == null)
            {
                return NotFound();
            }

            var tbCourseSection = await _context.tbCourseSections.FindAsync(id);
            if (tbCourseSection == null)
            {
                return NotFound();
            }
            ViewData["CourseTitle_FK"] = new SelectList(_context.tbCourses, "CourseTitle_PK", "CourseTitle_PK", tbCourseSection.CourseTitle_FK);
            ViewData["TeacherID_FK"] = new SelectList(_context.tbTeachers, "TeacherID_PK", "TeacherID_PK", tbCourseSection.TeacherID_FK);
            return View(tbCourseSection);
        }

        // POST: TeacherPort/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CourseSectionID_PK,Course_day,Course_time,AttendentNumber,ClassRoom,TeacherID_FK,CourseTitle_FK")] tbCourseSection tbCourseSection)
        {
            if (id != tbCourseSection.CourseSectionID_PK)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tbCourseSection);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!tbCourseSectionExists(tbCourseSection.CourseSectionID_PK))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CourseTitle_FK"] = new SelectList(_context.tbCourses, "CourseTitle_PK", "CourseTitle_PK", tbCourseSection.CourseTitle_FK);
            //ViewData["TeacherID_FK"] = new SelectList(_context.tbTeachers, "TeacherID_PK", "TeacherID_PK", tbCourseSection.TeacherID_FK);
            return View(tbCourseSection);
        }

        // GET: TeacherPort/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.tbCourseSections == null)
            {
                return NotFound();
            }

            var tbCourseSection = await _context.tbCourseSections
                .Include(t => t.CourseTitle_FKNavigation)
                .Include(t => t.TeacherID_FKNavigation)
                .FirstOrDefaultAsync(m => m.CourseSectionID_PK == id);
            if (tbCourseSection == null)
            {
                return NotFound();
            }

            return View(tbCourseSection);
        }

        // POST: TeacherPort/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.tbCourseSections == null)
            {
                return Problem("Entity set 'Team105DBContext.tbCourseSections'  is null.");
            }
            var tbCourseSection = await _context.tbCourseSections.FindAsync(id);
            if (tbCourseSection != null)
            {
                _context.tbCourseSections.Remove(tbCourseSection);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool tbCourseSectionExists(int id)
        {
          return (_context.tbCourseSections?.Any(e => e.CourseSectionID_PK == id)).GetValueOrDefault();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <title>@ViewData["Title"] - BullDog High School</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BullDoghs.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <img src="~/images/bulldoglogo.jpg" />
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                @*<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Bulldog High School </a>*@
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Course" asp-action="CourseView">All Courses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Course" asp-action="RegistrationView">All Registrations</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="StudentPort" asp-action="StudentView">Student Portal</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TeacherPort" asp-action="Index">Teacher Portal</a>
                        </li>
          
                        
                        <li class="nav-item">

                            @*If the user is authenticated, show Logout; else Login/Register*@

                            @{
                                bool identity = Context.User.Identity?.IsAuthenticated ?? false;

                                if (identity)
                                {
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                                }
                                else
                                {
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login/Sign Up</a>
                                }
                            }
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - Bulldog High School Student course registration system  Ceated by GANG YANG and ALEX WITTE.
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>


